#!/bin/sh
set -eu

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

API_MIN=21
API_MAX=32

for api in $(seq "${API_MIN}" 1 "${API_MAX}"); do
	for abi in aarch64-linux-android armv7a-linux-androideabi x86_64-linux-android i686-linux-android; do
		ln -snf ../target_wrapper "${SCRIPT_DIR}/bin/${abi}${api}-clang"
		ln -snf ../target_wrapper "${SCRIPT_DIR}/bin/${abi}${api}-clang++"
	done
done
